import type { Metadata } from "next";
import { Montserrat, Charm } from "next/font/google";






import "./globals.css";


const montserrat = Montserrat({
  variable: "--font-inter",
  subsets: ["latin", "vietnamese"],
});

const charm = Charm({
  weight: ["400", "700"],
  variable: "--font-charm",
  subsets: ["latin", "vietnamese"],
});







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montserrat.variable} ${charm.variable} h-full antialiased`}






    >

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
